version: "3.9"

x-common-variables: &common-variables
  STRIPE_PUBLIC_KEY: $STRIPE_PUBLIC_KEY
  STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
  DOMAIN: $DOMAIN
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_SERVER: $POSTGRES_SERVER
  DB_PORT: $DB_PORT
  SECRET_KEY: $SECRET_KEY


services:
  web:
    image: gmoroz/stripe-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      *common-variables
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    environment:
      *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
