version: "3.9"

services:
  web:
    image: gmoroz/stripe-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      .env
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
